on:
  push:
    branches: [newBranch]
  pull_request:
    branches: [newBranch]
 
jobs:
  databricks-quality-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
 
      - name: Trigger Databricks Job
        id: run_databricks_job
        uses: databricks/run-notebook@v0
        with:
          databricks-host: ${{ secrets.DATABRICKS_HOST }}
          databricks-token: ${{ secrets.DATABRICKS_TOKEN }}
          workspace-notebook-path: /Workspace/Users/traininguser4@sudosu.ai/case_study
          existing-cluster-id: ${{ secrets.DATABRICKS_CLUSTER_ID }}
 
      - name: Download Deequ Report (if failed)
        if: failure()
        run: |
          # Optionally fetch report from DBFS to attach as artifact using databricks' CLI or REST API
          echo "Deequ failed — see DBFS report"
 